version: '2'
services:
    db:
        image: mysql:5.6
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
    app:
        build: app/.
        volumes:
            - ./app/php.ini:/usr/local/etc/php/php.ini
            - ./data/magento/:/opt/magento/
        links:
            - db
    http:
        image: nginx:1.10.1
        volumes:
            - ./http/nginx-magento.conf:/etc/nginx/nginx-magento.conf
            - ./http/default.conf:/etc/nginx/conf.d/default.conf
            - ./data/magento/:/opt/magento/
        links:
            - app:php
        ports:
            - "80:80"