version: '2'
services:
    db:
        image: mysql:5.6
        volumes:
            - "~/magento/databse:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    app:
        build: app/.
        volumes:
            - /home/docker/data/app/php.ini:/usr/local/etc/php/php.ini
            - "~/magento/magento2:/opt/magento/"
        links:
            - db
    http:
        build: http/.
        volumes:
            - /home/docker/data/http/nginx-magento.conf:/etc/nginx/nginx-magento.conf
            - /home/docker/data/http/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - app
        ports:
            - "80:80"