version: '2'
services:
    fs:
        image: tianon/true
        volumes:
            - /opt/magento/
    database:
        image: mysql:5.6
        volumes:
            - ./db/:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
    app:
        build: app/.
        volumes:
            - ~/.composer/auth.json:/tmp/auth.json
            - ./app/php.ini:/usr/local/etc/php/php.ini
            - ./app/setup.sh:/usr/local/bin/setup.sh
        volumes_from:
            - fs
        links:
            - database
    http:
        image: nginx:1.10.1
        volumes:
            - ./http/nginx-magento.conf:/etc/nginx/nginx-magento.conf
            - ./http/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - fs
        links:
            - app:php
        ports:
            - "80:80"
